const APP_LOGO='assets/app-dark.png', SYS_LOGO='assets/provenanceos-dark.png';
const app=document.getElementById('app');
let samples=JSON.parse(localStorage.getItem('pos_samples')||'[]');
let stream=null;
const nextId=()=>`AND-${String(samples.length+1).padStart(6,'0')}`;
function shell(active='Home',body=''){
 app.innerHTML=`<div class="shell"><aside class="rail"><div class="brand"><img src="${APP_LOGO}" alt="Australian Provenance Project"><div class="system"><img src="${SYS_LOGO}"> <span>ProvenanceOS</span></div></div><nav class="nav">${['Home','Samples','Analysis','Provenance','Settings'].map(x=>`<button class="${x===active?'active':''}" onclick="navigate('${x}')">${x}</button>`).join('')}</nav></aside><main class="content">${body}</main><div class="toast" id="toast"></div></div>`;
}
function home(){shell('Home',`<div class="top"><div><div class="eyebrow">Australian Provenance Project</div><h1 class="title">The physical record,<br>made permanent.</h1><div class="sub">A quiet interface for registering stones, evidence and analysis.</div></div><button class="primary" onclick="newSample()">＋ New sample</button></div><div class="grid"><section class="card hero"><div class="hero-inner"><span class="pill"><i class="dot"></i> ProvenanceOS live</span><h2>Every stone has a story. Give it an identity.</h2><p>Capture the specimen, preserve its context, then connect the analytical record — from field collection to pXRF and beyond.</p><div class="stats"><div class="stat"><b>${samples.length}</b><span>Samples</span></div><div class="stat"><b>${samples.filter(s=>s.analysis).length}</b><span>Analysed</span></div><div class="stat"><b>${samples.filter(s=>s.images?.length).length}</b><span>Photographed</span></div></div></div></section><section class="card pad"><div class="section-title">Recent specimens</div><div class="sample-list">${samples.length?samples.slice(-5).reverse().map(sampleRow).join(''):`<div style="padding:35px 8px;color:#78868b">No samples yet.<br><br><button class="primary" onclick="newSample()">Register the first stone</button></div>`}</div></section></div>`)}
function sampleRow(s){return `<button class="sample" onclick="viewSample('${s.id}')"><div class="thumb"></div><div style="text-align:left"><strong>${s.id}</strong><small>${s.type||'Rough opal'} · ${s.location||'Location not recorded'}</small></div><div class="chev">${s.analysis?'Analysed':'Registered'}　›</div></button>`}
function newSample(){
 const id=nextId();
 app.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><div><div class="eyebrow">New sample</div><h2 style="font-size:31px;font-weight:300;margin:7px 0">${id}</h2><div class="sub">Register the physical specimen before analysis.</div></div><button class="close" onclick="closeModal()">×</button></div><div class="camera" id="camera"><div class="hint">Camera ready when you are</div></div><div class="actions" style="justify-content:flex-start;margin-top:12px"><button class="secondary" onclick="startCamera()">Open camera</button><label class="secondary" style="cursor:pointer">Choose photo<input id="photo" type="file" accept="image/*" capture="environment" hidden onchange="previewPhoto(event)"></label></div><div class="fields"><div class="field"><label>Location</label><input id="location" value="Andamooka, South Australia"></div><div class="field"><label>Sample type</label><select id="type"><option>Rough opal</option><option>Cut opal</option><option>Polished opal</option><option>Host material</option></select></div><div class="field"><label>Weight (g)</label><input id="weight" inputmode="decimal" placeholder="Optional"></div><div class="field"><label>Dimensions</label><input id="dimensions" placeholder="mm × mm × mm"></div><div class="field full"><label>Notes</label><textarea id="notes" placeholder="Anything worth preserving about this specimen…"></textarea></div></div><div class="actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveSample('${id}')">Register sample</button></div></div></div>`);
}
function startCamera(){const c=document.getElementById('camera');if(!navigator.mediaDevices?.getUserMedia){c.innerHTML='<div class="hint">Camera is unavailable in this browser. Choose a photo instead.</div>';return}navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false}).then(s=>{stream=s;c.innerHTML='<video autoplay playsinline></video>';c.querySelector('video').srcObject=s}).catch(()=>c.innerHTML='<div class="hint">Camera permission was declined. Choose a photo instead.</div>')}
function previewPhoto(e){const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f);document.getElementById('camera').innerHTML=`<img src="${url}" style="width:100%;max-height:360px;object-fit:cover">`;window._photoFile=f}
function saveSample(id){const s={id,location:document.getElementById('location').value,type:document.getElementById('type').value,weight:document.getElementById('weight').value,dimensions:document.getElementById('dimensions').value,notes:document.getElementById('notes').value,created:new Date().toISOString(),images:window._photoFile?[window._photoFile.name]:[],analysis:null};samples.push(s);localStorage.setItem('pos_samples',JSON.stringify(samples));window._photoFile=null;closeModal();viewSample(id);toast('Sample registered · '+id)}
function closeModal(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}document.getElementById('modal')?.remove()}
function viewSample(id){const s=samples.find(x=>x.id===id);if(!s)return;shell('Samples',`<div class="top"><div><div class="eyebrow">Sample record</div><h1 class="title">${s.id}</h1><div class="sub">${s.type} · ${s.location}</div></div><button class="primary" onclick="attachAnalysis('${s.id}')">＋ Attach pXRF</button></div><div class="sample-page"><section class="card photo-card"><div class="label"><span class="pill">${s.images?.length?'Photographed':'No image yet'}</span></div></section><section class="card detail"><div class="eyebrow">Identity</div><h2 style="font-size:30px;font-weight:300;margin:7px 0">${s.id}</h2><div class="sub">Registered ${new Date(s.created).toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'})}</div><div class="tabs"><button class="active">Overview</button><button>Evidence</button><button>Analysis</button><button>History</button></div><div class="fields" style="margin-top:0"><div><div class="section-title">Location</div><div>${s.location}</div></div><div><div class="section-title">Weight</div><div>${s.weight||'—'}${s.weight?' g':''}</div></div><div><div class="section-title">Dimensions</div><div>${s.dimensions||'—'}</div></div><div><div class="section-title">Notes</div><div>${s.notes||'—'}</div></div></div>${s.analysis?`<div style="margin-top:35px"><div class="section-title">pXRF analysis · ${s.analysis.instrument}</div><div class="analysis">${Object.entries(s.analysis.results).map(([k,v])=>`<div class="element"><span>${k}</span><b>${v}</b></div>`).join('')}</div></div>`:`<div style="margin-top:45px;padding:22px;border:1px solid rgba(255,255,255,.08);border-radius:20px;background:rgba(255,255,255,.03)"><div class="section-title">Analysis</div><div style="font-size:15px">No pXRF record attached.</div><div class="sub">Import the Vanta export when the scan is complete.</div></div>`}</section></div>`)}
function attachAnalysis(id){const s=samples.find(x=>x.id===id);s.analysis={instrument:'Vanta Max',method:'Geochem Mode',results:{Si:'32.48 %',Al:'10.32 %',Fe:'4.21 %',Ca:'8.76 %',K:'3.12 %',Ti:'1.08 %'}};localStorage.setItem('pos_samples',JSON.stringify(samples));viewSample(id);toast('pXRF record attached · demo data')}
function samplesPage(){shell('Samples',`<div class="top"><div><div class="eyebrow">Collection</div><h1 class="title">Samples</h1><div class="sub">The physical record of every registered specimen.</div></div><button class="primary" onclick="newSample()">＋ New sample</button></div><div class="card pad"><div class="sample-list">${samples.length?samples.map(sampleRow).join(''):'<div style="padding:40px;color:#78868b">Nothing registered yet.</div>'}</div></div>`)}
function analysisPage(){shell('Analysis',`<div class="top"><div><div class="eyebrow">Instrument data</div><h1 class="title">Analysis</h1><div class="sub">pXRF records connected to physical samples.</div></div></div><div class="card pad"><div class="sample-list">${samples.filter(s=>s.analysis).map(sampleRow).join('')||'<div style="padding:40px;color:#78868b">No Vanta results attached yet.</div>'}</div></div>`)}
function navigate(x){if(x==='Home')home();else if(x==='Samples')samplesPage();else if(x==='Analysis')analysisPage();else shell(x,`<div class="top"><div><div class="eyebrow">ProvenanceOS</div><h1 class="title">${x}</h1><div class="sub">This surface is ready for the next layer of the system.</div></div></div><div class="card pad"><div style="font-size:17px">${x==='Provenance'?'Every event will become part of the stone’s permanent history.':'System controls and account configuration will live here.'}</div></div>`)}
function toast(t){const x=document.getElementById('toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
home();
